export const UGANDAN_DISTRICTS = [
  "Abim", "Adjumani", "Agago", "Alebtong", "Amolatar", "Amudat", "Amuria", "Amuru", "Apac", "Arua",
  "Budaka", "Bududa", "Bugiri", "Bugweri", "Buhweju", "Buikwe", "Bukedea", "Bukomansimbi", "Bukwo", "Bulambuli", "Buliisa", "Bundibugyo", "Bunyangabu", "Bushenyi", "Busia", "Busotye", "Butaleja", "Butambala", "Butebo", "Buvuma", "Buyende",
  "Dokolo",
  "Entebbe",
  "Fort Portal",
  "Gomba", "Gulu",
  "Hoima",
  "Ibanda", "Iganga", "Isingiro",
  "Jinja",
  "Kaabong", "Kabale", "Kabarole", "Kaberamaido", "Kagadi", "Kakumiro", "Kalangala", "Kaliro", "Kalungu", "Kampala", "Kamuli", "Kamwenge", "Kanungu", "Kapchorwa", "Kapelebyong", "Kasanda", "Kasese", "Katakwi", "Kayunga", "Kazo", "Kibaale", "Kiboga", "Kibuku", "Kikuube", "Kiruhura", "Kiryandongo", "Kisoro", "Kitgum", "Koboko", "Kole", "Kotido", "Kumi", "Kwania", "Kween", "Kyankwanzi", "Kyegegwa", "Kyenjojo", "Kyotera",
  "Lamwo", "Lira", "Luuka", "Luwero", "Lwengo", "Lyantonde",
  "Madi-Okollo", "Manafwa", "Maracha", "Masaka", "Masindi", "Mayuge", "Mbale", "Mbarara", "Mitooma", "Mityana", "Moroto", "Moyo", "Mpigi", "Mubende", "Mukono", "Musingo",
  "Nabilatuk", "Nakapiripirit", "Nakaseke", "Nakasongola", "Namayingo", "Namisindwa", "Namutumba", "Napak", "Nebbi", "Ngora", "Ntoroko", "Ntungamo", "Nwoya",
  "Obongi", "Omoro", "Otuke", "Oyam",
  "Pader", "Pakwach", "Pallisa",
  "Rakai", "Rubanda", "Rubirizi", "Rukiga", "Rukungiri", "Rwampala",
  "Sembabule", "Serere", "Sheema", "Sironko", "Soroti",
  "Terego",
  "Wakiso", "Yumbe", "Zombo"
].sort();
